ZscalerCribl_CL
| where not(disabled)
| where array_index_of(AsimSchemas, 'WebSession') >= 0
| where (isnull(starttime) or TimeGenerated >= starttime) and (isnull(endtime) or TimeGenerated < endtime)
| where array_length(srcipaddr_has_any_prefix) == 0 or has_any_ipv4_prefix(SrcIpAddr, srcipaddr_has_any_prefix)
| where array_length(ipaddr_has_any_prefix) == 0 or has_any_ipv4_prefix(SrcIpAddr, ipaddr_has_any_prefix) or has_any_ipv4_prefix(DstIpAddr, ipaddr_has_any_prefix)
| where array_length(url_has_any) == 0 or Url has_any (url_has_any)
| where array_length(httpuseragent_has_any) == 0 or HttpUserAgent has_any (httpuseragent_has_any)
| where array_length(eventresultdetails_in) == 0 or EventResultDetails in~ (eventresultdetails_in)
| where eventresult == '*' or EventResult =~ eventresult
| where array_length(eventresultdetails_has_any) == 0 or EventResultDetails has_any (eventresultdetails_has_any)
| extend EventSchema='WebSession', EventSchemaVersion='0.2.7', EventVendor='Zscaler',
    AdditionalFields=bag_merge(iff(isnull(AdditionalFields), dynamic({}), AdditionalFields), bag_pack('ZscalerFamily', ZscalerFamily, 'ZscalerSubfamily', ZscalerSubfamily))
| project TimeGenerated, EventStartTime, EventEndTime, EventSchema, EventSchemaVersion,
    EventVendor, EventProduct, EventProductVersion, EventType, EventSubType, EventResult, EventResultDetails,
    EventOriginalResultDetails, EventOriginalType, EventOriginalUid, EventUid, EventCount, EventSeverity,
    EventOriginalSeverity, EventMessage, RuleName, SrcIpAddr, SrcPortNumber, SrcNatIpAddr,
    SrcNatPortNumber, SrcUsername, SrcUsernameType, SrcUserId, SrcHostname, SrcGeoCountry, SrcGeoCity,
    DstIpAddr, DstPortNumber, DstNatIpAddr, DstNatPortNumber, DstUsername, DstUsernameType,
    DstUserId, DstHostname, DstFQDN, DstGeoCountry, DstGeoCity, DstAppName, DstAppType,
    DvcHostname, DvcIpAddr, DvcAction, NetworkProtocol, NetworkApplicationProtocol,
    NetworkDirection, NetworkDuration, NetworkBytes, SrcBytes, DstBytes, NetworkSessionId,
    Url, UrlCategory, HttpRequestMethod, HttpStatusCode, HttpUserAgent, HttpReferrer, HttpContentType,
    ThreatName, ThreatCategory, ThreatRiskLevel, AdditionalFields
