ZscalerCribl_CL
| where not(disabled)
| where array_index_of(AsimSchemas, 'FileEvent') >= 0
| where (isnull(starttime) or TimeGenerated >= starttime) and (isnull(endtime) or TimeGenerated < endtime)
| where array_length(eventtype_in) == 0 or EventType in~ (eventtype_in)
| where array_length(srcipaddr_has_any_prefix) == 0 or has_any_ipv4_prefix(SrcIpAddr, srcipaddr_has_any_prefix)
| where array_length(actorusername_has_any) == 0 or ActorUsername has_any (actorusername_has_any)
| where array_length(targetfilepath_has_any) == 0 or TargetFilePath has_any (targetfilepath_has_any)
| where array_length(srcfilepath_has_any) == 0 or SrcFilePath has_any (srcfilepath_has_any)
| where array_length(hashes_has_any) == 0 or TargetFileMD5 has_any (hashes_has_any) or TargetFileSHA1 has_any (hashes_has_any) or TargetFileSHA256 has_any (hashes_has_any)
| where array_length(dvchostname_has_any) == 0 or DvcHostname has_any (dvchostname_has_any)
| extend EventSchema='FileEvent', EventSchemaVersion='0.2.1', EventVendor='Zscaler',
    AdditionalFields=bag_merge(iff(isnull(AdditionalFields), dynamic({}), AdditionalFields), bag_pack('ZscalerFamily', ZscalerFamily, 'ZscalerSubfamily', ZscalerSubfamily))
| project TimeGenerated, EventStartTime, EventEndTime, EventSchema, EventSchemaVersion,
    EventVendor, EventProduct, EventProductVersion, EventType, EventSubType, EventResult, EventResultDetails,
    EventOriginalResultDetails, EventOriginalType, EventOriginalUid, EventUid, EventCount, EventSeverity,
    EventOriginalSeverity, EventMessage, RuleName, ActorUsername, ActorUsernameType, ActorUserId,
    SrcIpAddr, SrcHostname, DvcHostname, DvcIpAddr,
    TargetFilePath, TargetFileName, TargetFileExtension, TargetFileMD5, TargetFileSHA1,
    TargetFileSHA256, TargetFileSHA512, TargetFileSize, TargetFileContentType,
    TargetFileCreationTime, TargetFileModificationTime, TargetFileOwner, SrcFilePath, SrcFileName, ThreatName,
    ThreatCategory, ThreatRiskLevel, AdditionalFields
