ZscalerCribl_CL
| where not(disabled)
| where array_index_of(AsimSchemas, 'Dns') >= 0
| where (isnull(starttime) or TimeGenerated >= starttime) and (isnull(endtime) or TimeGenerated < endtime)
| where srcipaddr == '*' or SrcIpAddr == srcipaddr
| where array_length(domain_has_any) == 0 or DnsQuery has_any (domain_has_any)
| where responsecodename == '*' or DnsResponseCodeName =~ responsecodename
| where response_has_ipv4 == '*' or tostring(DnsResponseName) has response_has_ipv4
| where array_length(response_has_any_prefix) == 0 or tostring(DnsResponseName) has_any (response_has_any_prefix)
| where eventtype in~ ('*', 'lookup', 'Query') or EventType =~ eventtype
| extend EventSchema='Dns', EventSchemaVersion='0.1.7', EventVendor='Zscaler',
    AdditionalFields=bag_merge(iff(isnull(AdditionalFields), dynamic({}), AdditionalFields), bag_pack('ZscalerFamily', ZscalerFamily, 'ZscalerSubfamily', ZscalerSubfamily))
| project TimeGenerated, EventStartTime, EventEndTime, EventSchema, EventSchemaVersion,
    EventVendor, EventProduct, EventProductVersion, EventType, EventSubType, EventResult, EventResultDetails,
    EventOriginalResultDetails, EventOriginalType, EventOriginalUid, EventUid, EventCount, EventSeverity,
    EventOriginalSeverity, EventMessage, RuleName, SrcIpAddr, SrcPortNumber, SrcUsername,
    SrcUsernameType, SrcUserId, SrcHostname, SrcGeoCountry, DstIpAddr, DstPortNumber,
    DnsQuery, DnsQueryTypeName, DnsResponseCodeName, DnsResponseName, NetworkProtocol,
    DnsNetworkDuration, NetworkBytes, SrcBytes, DstBytes, DvcHostname, DvcIpAddr, AdditionalFields
